---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-password
type: Opaque
data:
  db-password: UEBzc3cwcmQxMjM0IQ==


####Use as below format required#####
#- name: db-password
#  valueFrom:
#   secretKeyRef:
#     name: mysql-db-password
#     key: db-password

# We can have multiple key value pairs of secrets under 'data' and access them in deployments, services etc..