---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  clusterIP: None     #Pod IP will be used instead of assigning a clusterIP(this is called headless service)
  
