---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-service   # # NGINX proxy pass is coded with this name so the name cannot be different
  labels:
    tier: backend
    name: backend-svc
spec:
  type: ClusterIP # Default Service Type and it is optional to specify explicitly
  selector:
    tier: backend
    name: app-backend
  ports:
    - name: http
      port: 8080            # ClusterIP Service Port
      targetPort: 8080    # Backend Pod's containerPort where the application is running

