---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nginxapp-loadbalancer-service
  labels:
    tier: frontend
    name: frontend-svc
spec:
  type: LoadBalancer
  selector:
      tier: frontend
      name: app-frontend
  ports:
    - name: http
      port: 8080
      targetPort: 80   # Frontend Pod's containerPort where the application is running