---
apiVersion: v1
kind: Namespace
metadata:
  name: dev3

--- # ResourceQuota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-resourcequota
  namespace: dev3
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: '2'
    limits.memory: 2Gi
    pods: '5'
    persistentvolumeclaims: '5'
    requests.storage: 5Gi
    secrets: '5'
    services: '5'
    configmaps: '5'

---   # LimitRange
apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-memory-limit-range
  namespace: dev3
spec:
  limits:
  # 'default' and 'defaultRequest' may not be specified when type is 'Pod'
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "200m"
      memory: "256Mi"