---
apiVersion: v1
kind: Service
metadata:
  name: deployment-loadbalancer-service
spec:
  type: LoadBalancer
  selector:       # here we define the labels of the pods which will be targeted by this service
    app: myapp3
  ports:
    - name: http
      protocol: TCP
      port: 80            # Service Port
      targetPort: 80      # Container Port defined in the Pod template of ReplicaSet